# Composite action needed to access github context

# This is to compensate for yarn 3 issue https://github.com/yarnpkg/berry/issues/3868
name: 'Build in docker'
description: 'This will remove stableVersion from packages for prerelease'

  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        docker build -v ${{github.workspace}}/target:/subql/target .
      shell: sh