# Composite action needed to access github context

# This is to compensate for yarn 3 issue https://github.com/yarnpkg/berry/issues/3868
name: 'Build in docker'
description: 'This will remove stableVersion from packages for prerelease'
inputs:
  arch:
    description: 'amd64|arm64'
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    -
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: network=host
    - name: Build builder
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: amd64
        file: .github/actions/build-in-docker/Dockerfile
        context: .
        tags: localhost:5000/dep-builder:latest
        cache-from: type=local,src=/tmp/.buildx-cache/builder
        cache-to: type=local,dest=/tmp/.builder-new,mode=max
    - name: Build
      run: |
        docker images
        mkdir -p "/tmp/.buildx-cache/${{inputs.arch}}/target"
        mkdir -p "/tmp/.buildx-cache/${{inputs.arch}}/.cargo"
        docker run --rm -v /tmp/.buildx-cache/${{inputs.arch}}/target:/subql/target -v /tmp/.buildx-cache/${{inputs.arch}}/.cargo:/root/.cargo localhost:5000/dep-builder /bin/sh -c "cargo build --release && rm -f target/release/deps/libsubql_utils*"
        docker create --name builder localhost:5000/dep-builder
        docker cp /tmp/.buildx-cache/${{inputs.arch}}/target builder:/subql
        docker cp /tmp/.buildx-cache/${{inputs.arch}}/.cargo builder:/root
        docker commit builder localhost:5000/dep-builder:latest
        docker push localhost:5000/dep-builder:latest
      shell: bash
    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache/builder
        mv /tmp/.builder-new /tmp/.buildx-cache/builder
      shell: bash
