# Composite action needed to access github context

# This is to compensate for yarn 3 issue https://github.com/yarnpkg/berry/issues/3868
name: 'Build in docker'
description: 'This will remove stableVersion from packages for prerelease'
inputs:
  arch:
    description: 'amd64|arm64'
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    -
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build
      run: |
        docker build -t tmp -f .github/actions/build-in-docker/Dockerfile . 
        mkdir -p "/tmp/.buildx-cache/${{inputs.arch}}/target"
        cp -r "/tmp/.buildx-cache/${{inputs.arch}}/target" .
        docker run --rm -v ${{github.workspace}}/target:/subql/target tmp /bin/sh -c "cargo build --release && rm -f target/release/deps/libsubql_utils*"
        rm -rf /tmp/.buildx-cache/${{inputs.arch}}/target
        cp -r target /tmp/.buildx-cache/${{inputs.arch}}
      shell: bash