# Composite action needed to access github context

# This is to compensate for yarn 3 issue https://github.com/yarnpkg/berry/issues/3868
name: 'Build in docker'
description: 'This will remove stableVersion from packages for prerelease'
inputs:
  cachedir:
    description: 'the path of cachedir'
    required: true

  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    -
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build
      run: |
        docker build -t tmp -f .github/actions/build-in-docker/Dockerfile . 
        [ -f "${{inputs.cachedir}}/target" ] && cp -r "${{inputs.cachedir}}"/target .
        mkdir -p target
        docker run --rm -v ${{github.workspace}}/target:/subql/target tmp /bin/sh -c "cargo build --release && rm -f target/release/deps/libsubql_utils*"
        rm -rf ${{inputs.cachedir}}/target
        cp -r target ${{inputs.cachedir}}
      shell: bash