version: "3"

services:
  proxy-redis:
    image: redis:7-alpine
    container_name: coordinator_cache
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  proxy-server:
    image: onfinality/subql-indexer-proxy:v0.3.0-1
    container_name: coordinator_proxy
    ports:
      - 80:80
    depends_on:
      "coordinator-service":
        condition: service_healthy
    restart: always
    command:
      - --port=80
      - --host=0.0.0.0
      - --auth
      - --debug
      - --network=moonbase
      - --network-endpoint=https://moonbeam-alpha.api.onfinality.io/public
      - --token-duration=8 # query auth token validity [hours]
      - --secret-key=vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3
      - --service-url=http://coordinator-service:8000/graphql
      - --redis-endpoint=redis://coordinator_cache
networks:
  default:
    external:
      name: cooridnator-service
