name: Develop

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
    - name: check fmt
      run: cargo fmt -- --check
    - name: check lint
      run: cargo clippy --workspace
    - name: check test
      run: cargo test
