name: discord3
on:
  release:
    types:
      - published

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest

    steps:
      - name: Get release details
        id: release
        run: |
          echo "New release: ${{ github.event.release.name || github.event.release.tag_name }} ${{ github.event.release.type }}"
          echo ""
          echo "${{ github.event.release.body }}"
          echo ""
          echo "Release URL: ${{ github.event.release.html_url }}"
          echo "::set-output name=releaseName::${{ github.event.release.name || github.event.release.tag_name }}"
          echo "::set-output name=releaseBody::${{ github.event.release.body }}"
          echo "::set-output name=releaseUrl::${{ github.event.release.html_url }}"

      - name: Send release details to Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: ${{ github.event.release.body }}
          text: ${{ github.event.release.name }}
